### ISSUE TITLE
Could you please expose caniuse mod?

### ISSUE THREAD

**Issue by IWANABETHATGUY** [g-plane/browserslist-rs#2]
Thanks for what you did for this project, we are planing to port the autoprefixer in rust, we found this project which is super nice. but the caniuse mod is not expose, so i am wonder if you are willing to expose it?

**Comment by g-plane** [comment]
It looks you need the Can I Use data. Am I right?

**Comment by IWANABETHATGUY** [comment]
> I guess you need the Can I Use data. Am I right?

yes, our usage is is the same as `can-i-use-lite`

**Comment by g-plane** [comment]
The data format of Can I Use in this project is completely different from "caniuse-lite", and I can't guarantee the stability of its format.

I don't mind exposing it, but how we can keep it stable will be a problem.

**Comment by g-plane** [comment]
I may split it as a separated crate in the future.

**Comment by IWANABETHATGUY** [comment]
> I may split it as a separated crate in the future.

That sounds very nice

**Comment by g-plane** [comment]
However, can you state your requirements of data structure? Current structure is optimized for this project only, and it may not be suitable for public use.

**Comment by g-plane** [comment]
Close due to no response.
