### ISSUE TITLE
Browserslist wasm with web interface

### ISSUE THREAD

**Issue by le0pard** [g-plane/browserslist-rs#4]
Hello.

I am have idea to build browserslist wasm with web interface, which will work even offline (by using service worker). I found your project and I want to thanks for great job. 

I am start build wasm module based on your library, but now find out you also doing some work with it too (based on commits). I decided to ask, maybe you have similar idea and in this case I don't need waste time on this. Or maybe you working on the wasm module for some different needs (maybe it will be published as npm package)?

P.S. Big thanks for code. I did try to load rust was module, but looks like it return names only for firefox browsers:

```js
  import init, {browserslist} from './../browserslist-wasm/pkg'

  init().then(() => {
    console.log(browserslist('>1%, Firefox ESR, not dead, not ie 11, not op_mini all'))
  })
```

I uploaded code here (if you want check yourself): https://github.com/le0pard/browserlist
 
![Screenshot 2021-12-09 at 01 01 21](https://user-images.githubusercontent.com/98444/145305031-2c6af863-dc7b-4ed1-8287-71b3411ebe35.png)

**Comment by g-plane** [comment]
I've tested based on the latest commit, not the 0.4.0 version, and I can't reproduce it, but maybe there're some fixes between the released version and the latest commit. You can try it again once I release new version and provide feedback if it still doesn't work.

Currently I don't have plans on publishing WebAssembly build to npm.

**Comment by le0pard** [comment]
@g-plane thanks, I will try HEAD to build wasm module. And thanks for information
