### ISSUE TITLE
Wasm module not contain all data, as rust package

### ISSUE THREAD

**Issue by le0pard** [g-plane/browserslist-rs#5]
Thanks for your work. 

I am not a Rust developer, so I apologize in advance if the problem and question are stupid.

I am trying to use this library to made web page with wasm module (for fun). Wasm module works, you can check results here (it is draft, no design) - https://browserlist.leopard.in.ua/ (repo here - https://github.com/le0pard/browserlist )

Looks like problem the same, as I mentioned in https://github.com/g-plane/browserslist-rs/issues/4#issue-1074920938 - library return versions without browser names. 

![image](https://user-images.githubusercontent.com/98444/146980857-2648873a-4ec5-4ccc-a412-5735d60ac035.png)

In `cargo run --example inspect -- <query>` everything works correctly. 

rustc version - 1.57.0 (f1edd0429 2021-11-29)
browserslist-rs taken from HEAD - https://github.com/le0pard/browserlist/blob/main/browserslist-wasm/Cargo.toml#L17

Build you can see here: https://github.com/le0pard/browserlist/runs/4598534242?check_suite_focus=true (used wasm-pack)

Is this possible, that wasm-pack doing some optimisation and remove from wasm package data, which package need for work?

Thanks for help.

**Comment by g-plane** [comment]
I can reproduce this bug when building with release mode. Previously I built with dev mode so I couldn't see this problem.

**Comment by g-plane** [comment]
https://github.com/g-plane/browserslist-rs/commit/5b4d19e652ad5589226dab09d1b52b8d6bfc9823 has fixed this issue.

**Comment by le0pard** [comment]
Big thanks @g-plane
